// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as OpenImport } from './routes/open'
import { Route as ClosedImport } from './routes/closed'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const OpenRoute = OpenImport.update({
  path: '/open',
  getParentRoute: () => rootRoute,
} as any)

const ClosedRoute = ClosedImport.update({
  path: '/closed',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/closed': {
      preLoaderRoute: typeof ClosedImport
      parentRoute: typeof rootRoute
    }
    '/open': {
      preLoaderRoute: typeof OpenImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  ClosedRoute,
  OpenRoute,
])
